#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "m4kainth/05290561@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

DROP TABLE ALBUMS;
DROP TABLE BOOKS
DROP TABLE BORROWED;
DROP TABLE BRANCHES;
DROP TABLE CATALOG;
DROP TABLE COMPUTER;
DROP TABLE EMPLOYEE;
DROP TABLE ITEM;
DROP TABLE MEMBERS;
DROP TABLE MOVIES;
DROP TABLE OFFERSROOM;
DROP TABLE RESERVEDCOMPUTER;
DROP TABLE RESERVEDROOM;
DROP TABLE ROOM;
DROP TABLE SUPERVISES;
DROP TABLE WORKS_FOR;

exit;
EOF
