#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "m4kainth/05290561@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "m4kainth/05290561@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

Insert into ALBUMS (ITEM_ID,ARTIST) values (4,'ZillaKami');
Insert into ALBUMS (ITEM_ID,ARTIST) values (8,'my bloody valentine');
Insert into ALBUMS (ITEM_ID,ARTIST) values (11,'SEPULTURA');
Insert into ALBUMS (ITEM_ID,ARTIST) values (9,'Nirvana');
Insert into ALBUMS (ITEM_ID,ARTIST) values (1,'Kendrick Lamar');

Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,6);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,1);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,2);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (10,4);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (10,6);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,7);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,8);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,9);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (13,11);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (12,14);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (12,15);

Insert into M4KAINTH.BOOKS (ITEM_ID,AUTHOR) values (2,'J.K. Rowling');
Insert into M4KAINTH.BOOKS (ITEM_ID,AUTHOR) values (6,'George Orwell');
Insert into M4KAINTH.BOOKS (ITEM_ID,AUTHOR) values (7,'Ray Bradbury');

Insert into M4KAINTH.BRANCHES (BRANCH_ID,ADDRESS,PROVINCE,CITY,POSTALCODE,LOCATION) values (1,'69 Bushberry Road','ON','Toronto','L7D1D3','Bushberry Library');
Insert into M4KAINTH.BRANCHES (BRANCH_ID,ADDRESS,PROVINCE,CITY,POSTALCODE,LOCATION) values (2,'72 Echodrive Street','ON','Brampton','M3V3D6','Echodrive Library');
Insert into M4KAINTH.BRANCHES (BRANCH_ID,ADDRESS,PROVINCE,CITY,POSTALCODE,LOCATION) values (3,'56 Yonge Street','ON','Toronto','N3D3H7','Yonge St Library');
Insert into M4KAINTH.BRANCHES (BRANCH_ID,ADDRESS,PROVINCE,CITY,POSTALCODE,LOCATION) values (4,'87 Steeplebush Road','ON','North York','L5H9G4','Steeplebush Library');
Insert into M4KAINTH.BRANCHES (BRANCH_ID,ADDRESS,PROVINCE,CITY,POSTALCODE,LOCATION) values (5,'212 Mercury Street','ON','Caledon','J68N5T','Mercury Library');

Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (1,1,2,0);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (1,2,3,4);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (1,4,4,6);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (1,8,2,7);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (1,11,5,2);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (2,3,4,6);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (2,5,6,3);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (2,9,12,0);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (2,10,5,5);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (3,7,1,4);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (3,1,5,2);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (3,6,1,5);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (3,5,2,4);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (3,7,3,5);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (4,6,3,7);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (4,7,3,7);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (4,8,2,8);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (5,11,3,5);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (5,6,2,6);
Insert into M4KAINTH.CATALOG (BRANCH_ID,ITEM_ID,QUANTITYONLOAN,QUANTITYAVAILABLE) values (5,5,4,3);

Insert into M4KAINTH.COMPUTER (COMPUTERID) values (1);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (2);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (3);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (4);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (5);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (6);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (7);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (8);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (9);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (10);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (11);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (12);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (13);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (14);
Insert into M4KAINTH.COMPUTER (COMPUTERID) values (15);

Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (1,'Mayank','Kainth','69 Grass Road','ON','Toronto','L162E5');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (2,'Adam','Khan','12 Cabbage Street','ON','Toronto','M7C3G6');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (3,'Angelo','Jerome','121 Amazing Road','ON','Toronto','M8B5C5');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (4,'Bobby','Bob','123 Nice Road','ON','Brampton','V4C2H6');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (5,'Joel','Smith','61 Function Street','ON','Caledon','N7B6V8');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (6,'Josh','Smith','61 Function Street','ON','Caledon','N7B6V8');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (7,'Sayeed','Jones','132 Cornerstuck Road','ON','Mississauga','C5N9F5');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (8,'Mary','White','987 Busan Road','ON','Missisauga','B7C8B7');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (9,'Genji ','Shimada','112 Hanamura Drive','ON','Mississauga','B8V5N8');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (10,'Moira','Brown','420 Blazeit Boulevard','ON','North York','B7V8V8');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (11,'Susan','Sue','176 Mercy Drive','ON','Scarborough','B7C9V0');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (12,'Ray','Grewal','134 Confederation Drive','ON','Etobicoke','H7C5J7');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (13,'Livjyot','Kainth','420 Love Street','ON','Brampton','G8B2M8');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (14,'Sagar','Shivrattan','69 McDonalds Road','ON','Brampton','H3H3H3');
Insert into M4KAINTH.EMPLOYEE (EMPLOYEE_ID,FNAME,LNAME,ADDRESS,PROVINCE,CITY,POSTALCODE) values (15,'Frank','Yusuf','162 Deep Street','ON','Etobicoke','G7D8B9');

Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (4,'DOGBOY',to_date('17-SEP-21','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (5,'Se7en',to_date('12-FEB-14','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (6,'1984',to_date('21-AUG-65','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (7,'Farenheit 451',to_date('31-JAN-67','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (8,'Loveless',to_date('21-JUN-04','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (9,'Nevermind',to_date('15-APR-91','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (11,'ROOTS',to_date('12-JUN-92','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (10,'Shutter Island',to_date('20-MAY-10','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (1,'To Pimp a Butterfly',to_date('09-DEC-89','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (2,'Harry Potter and the Prisoner of Azkaban',to_date('09-MAY-01','DD-MON-RR'));
Insert into M4KAINTH.ITEM (ITEM_ID,TITLE,RELEASEDATE) values (3,'Pulp Fiction',to_date('14-OCT-94','DD-MON-RR'));

Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (1,to_date('13-JUL-16','DD-MON-RR'),'Sayeed ','Dao');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (2,to_date('29-APR-16','DD-MON-RR'),'Bonson','Asim');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (3,to_date('09-FEB-22','DD-MON-RR'),'Daniyal','Yusuf');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (4,to_date('15-JUL-16','DD-MON-RR'),'Farson','Varela');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (5,to_date('06-FEB-09','DD-MON-RR'),'Robby','Sarai');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (6,to_date('09-MAY-13','DD-MON-RR'),'Joel','Prina');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (7,to_date('16-OCT-15','DD-MON-RR'),'Kyle','Dao');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (8,to_date('22-JUL-16','DD-MON-RR'),'Frank','DaTank');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (9,to_date('05-MAY-17','DD-MON-RR'),'Sagar','Syal');
Insert into M4KAINTH.MEMBERS (MEMBER_ID,JOINDATE,FNAME,LNAME) values (10,to_date('07-OCT-16','DD-MON-RR'),'Robby','Nijjar');

Insert into M4KAINTH.MOVIES (DIRECTOR,ITEM_ID) values ('David Fincher',5);
Insert into M4KAINTH.MOVIES (DIRECTOR,ITEM_ID) values ('Quentin Tarantino',3);
Insert into M4KAINTH.MOVIES (DIRECTOR,ITEM_ID) values ('Martin Scorsese',10);

Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (1,1);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (1,2);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (1,3);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (1,4);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (1,5);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (2,6);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (3,7);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (4,8);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (4,9);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (4,10);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (4,11);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (5,12);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (5,13);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (5,14);
Insert into M4KAINTH.OFFERSROOM (BRANCH_ID,ROOM_ID) values (5,15);

Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (2,6);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (3,4);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (5,7);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (6,8);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (7,7);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (10,1);
Insert into M4KAINTH.RESERVEDCOMPUTER (MEMBER_ID,COMPUTERID) values (6,7);

Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (2,5);
Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (5,6);
Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (3,8);
Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (1,6);
Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (7,4);
Insert into M4KAINTH.RESERVEDROOM (MEMBER_ID,ROOMID) values (10,3);

Insert into M4KAINTH.ROOM (ROOMID) values (1);
Insert into M4KAINTH.ROOM (ROOMID) values (2);
Insert into M4KAINTH.ROOM (ROOMID) values (3);
Insert into M4KAINTH.ROOM (ROOMID) values (4);
Insert into M4KAINTH.ROOM (ROOMID) values (5);
Insert into M4KAINTH.ROOM (ROOMID) values (6);
Insert into M4KAINTH.ROOM (ROOMID) values (7);
Insert into M4KAINTH.ROOM (ROOMID) values (8);
Insert into M4KAINTH.ROOM (ROOMID) values (9);
Insert into M4KAINTH.ROOM (ROOMID) values (10);
Insert into M4KAINTH.ROOM (ROOMID) values (11);
Insert into M4KAINTH.ROOM (ROOMID) values (12);
Insert into M4KAINTH.ROOM (ROOMID) values (13);
Insert into M4KAINTH.ROOM (ROOMID) values (14);
Insert into M4KAINTH.ROOM (ROOMID) values (15);

Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,6);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,1);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (5,2);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (10,4);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (10,6);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,7);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,8);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (3,9);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (13,11);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (12,14);
Insert into M4KAINTH.SUPERVISES (SUPERVISOR,SUPERVISEE) values (12,15);

Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (5,1);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (10,2);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (3,3);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (12,4);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (13,5);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (6,1);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (1,1);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (2,1);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (4,2);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (11,5);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (7,3);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (8,3);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (9,3);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (14,4);
Insert into M4KAINTH.WORKS_FOR (EMPLOYEE_ID,BRANCH_ID) values (15,4);

exit;
EOF
