#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "m4kainth/05290561@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

SELECT * FROM BOOKS;
SELECT * FROM ITEM;
SELECT * FROM CATALOG;
SELECT * FROM ALBUMS;
SELECT * FROM BRANCHES;
SELECT * FROM COMPUTER;
SELECT * FROM EMPLOYEE;
SELECT * FROM ITEM;
SELECT * FROM MEMBERS;
SELECT * FROM MOVIES;
SELECT * FROM OFFERSROOM;
SELECT * FROM RESERVEDCOMPUTER;
SELECT * FROM RESERVEDROOM;
SELECT * FROM ROOM;
SELECT * FROM SUPERVISES;
SELECT * FROM WORKS_FOR;

SELECT CATALOG.BRANCH_ID, CATALOG.ITEM_ID, CATALOG.QUANTITYONLOAN, CATALOG.QUANTITYAVAILABLE, BRANCHES.LOCATION, ITEM.TITLE FROM CATALOG
LEFT JOIN BRANCHES ON CATALOG.BRANCH_ID = BRANCHES.BRANCH_ID
LEFT JOIN ITEM ON CATALOG.ITEM_ID = ITEM.ITEM_ID
ORDER BY CATALOG.QUANTITYONLOAN DESC;

CREATE VIEW LIBRARYADDRESSES AS
SELECT BRANCH_ID, address
FROM BRANCHES;

SELECT ALBUMS.ITEM_ID, ALBUMS.ARTIST, ITEM.TITLE, ITEM.RELEASEDATE 
FROM ALBUMS 
LEFT JOIN ITEM
ON ALBUMS.ITEM_ID = ITEM.ITEM_ID;


SELECT MOVIES.ITEM_ID, MOVIES.DIRECTOR, ITEM.TITLE, ITEM.RELEASEDATE 
FROM MOVIES 
LEFT JOIN ITEM
ON MOVIES.ITEM_ID = ITEM.ITEM_ID;


SELECT BOOKS.ITEM_ID, BOOKS.AUTHOR, ITEM.TITLE, ITEM.RELEASEDATE 
FROM BOOKS 
LEFT JOIN ITEM
ON BOOKS.ITEM_ID = ITEM.ITEM_ID;


SELECT RESERVEDROOM.ROOMID, MEMBERS.MEMBER_ID, MEMBERS.FNAME, MEMBERS.LNAME FROM 
RESERVEDROOM
LEFT JOIN MEMBERS
ON MEMBERS.MEMBER_ID = RESERVEDROOM.MEMBER_ID


SELECT OFFERSROOM.BRANCH_ID, OFFERSROOM.ROOM_ID,BRANCHES.LOCATION FROM OFFERSROOM
LEFT JOIN BRANCHES ON OFFERSROOM.BRANCH_ID = BRANCHES.BRANCH_ID;


SELECT SUPERVISES.SUPERVISOR, SUPERVISES.SUPERVISEE, E1.FNAME AS SUPERVISOR_FNAME, E1.LNAME AS SUPERVISOR_LNAME, E2.FNAME as SUPERVISEE_FNAME, E2.LNAME AS SUPERVISEE_LNAME
FROM SUPERVISES
    LEFT JOIN (SELECT * FROM EMPLOYEE) E1 on E1.EMPLOYEE_ID = SUPERVISES.SUPERVISOR
    LEFT JOIN (SELECT * FROM EMPLOYEE) E2 ON E2.EMPLOYEE_ID = SUPERVISES.SUPERVISEE
ORDER BY SUPERVISES.SUPERVISOR;

exit;
EOF

